### ISSUE TITLE
call_user_func_array(): Argument #1 ($callback) must be a valid callback, class think\Template does not have a method "getFinder"

### ISSUE THREAD

**Issue by azpanel** [yangweijie/think-debugbar#1]
在 https://github.com/[azpanel/azpanel](https://github.com/azpanel/azpanel) 项目安装，设置 `config/debugbar.php` 配置文件，`collectors` 类 `db` 设为 `true` 就会这样

```
Call Stack
in Think.php line 257
at call_user_func_array() in Think.php line 257
at Think->__call() in Manager.php line 175
at Manager->__call() in SqlCollector.php line 491
at SqlCollector->findViewFromHash() in SqlCollector.php line 417
at SqlCollector->parseTrace() in SqlCollector.php line 369
at SqlCollector->findSource2() in SqlCollector.php line 254
at SqlCollector->addSql() in DebugBar.php line 285
at DebugBar->think\debugbar\{closure}() in Connection.php line 264
at Connection->trigger() in PDOConnection.php line 776
at PDOConnection->getPDOStatement() in Mysql.php line 66
at Mysql->getFields() in PDOConnection.php line 422
at PDOConnection->getTableFieldsInfo() in PDOConnection.php line 362
at PDOConnection->getSchemaInfo() in PDOConnection.php line 409
at PDOConnection->getTableInfo() in PDOConnection.php line 493
at PDOConnection->getFieldsType() in TableFieldInfo.php line 58
at Query->getFieldsType() in TableFieldInfo.php line 69
at Query->getFieldType()
at call_user_func_array() in Model.php line 1049
at Model->__call() in TimeStamp.php line 73
at Model->checkTimeFieldType() in TimeStamp.php line 54
at Model->isAutoWriteTimestamp() in ModelService.php line 35
at ModelService->think\service\{closure}()
at call_user_func() in Model.php line 242
at Model->__construct() in Model.php line 1058
at Model::__callStatic() in Config.php line 15
at Config::obtain() in c1d33f441c0311c9c5138049a6823b46.php line 206
at include('/home/wwwroot/azure/...') in File.php line 59
at File->read() in Template.php line 255
at Template->fetch() in Think.php line 149
at Think->fetch() in View.php line 90
at View->think\{closure}() in View.php line 126
at View->getContent() in View.php line 89
at View->fetch()
at call_user_func_array() in Facade.php line 96
at Facade::__callStatic() in UserAws.php line 22
at UserAws->index()
at ReflectionMethod->invokeArgs() in Container.php line 344
at Container->invokeReflectMethod() in Controller.php line 110
at Controller->think\route\dispatch\{closure}() in Pipeline.php line 59
at Pipeline->think\{closure}() in Pipeline.php line 66
at Pipeline->then() in Controller.php line 84
at Controller->exec() in Dispatch.php line 80
at Dispatch->run() in Route.php line 793
at Route->think\{closure}() in Pipeline.php line 59
at Pipeline->think\{closure}() in Pipeline.php line 66
at Pipeline->then() in Route.php line 792
at Route->dispatch() in Http.php line 216
at Http->dispatchToRoute() in Http.php line 206
at Http->think\{closure}() in Pipeline.php line 59
at Pipeline->think\{closure}() in SessionInit.php line 67
at SessionInit->handle()
at call_user_func() in Middleware.php line 142
at Middleware->think\{closure}() in Pipeline.php line 85
at Pipeline->think\{closure}() in InjectDebugbar.php line 30
at InjectDebugbar->handle()
at call_user_func() in Middleware.php line 142
at Middleware->think\{closure}() in Pipeline.php line 85
at Pipeline->think\{closure}() in TraceDebug.php line 71
at TraceDebug->handle()
at call_user_func() in Middleware.php line 142
at Middleware->think\{closure}() in Pipeline.php line 85
at Pipeline->think\{closure}() in Pipeline.php line 66
at Pipeline->then() in Http.php line 205
at Http->runWithRequest() in Http.php line 170
at Http->run() in index.php line 20
````

![屏幕截图 2024-07-12 143738](https://github.com/user-attachments/assets/a788379c-74e8-4961-9dd6-785ee9f49dee)

**Comment by yangweijie** [comment]
你装的哪个版本的 ？之前视图那边会报错 后来修复了，建议你将think-trace 卸载了试试

**Comment by azpanel** [comment]
开发者你好，感谢回复。目前情况是这样的。执行
```
composer require yangweijie/think-debugbar --dev
```
会安装v1.0.1版本，有这个问题。

指定安装1.0.6版本，在.env中配置打开debug条，已经卸载think-trace（下同），页面不显示。
降级到1.0.5版本，1.0.4版本，有错误
```
Uncaught TypeError: DebugBar\DataCollector\ExceptionsCollector::addException(): Argument #1 ($e) must be of type Exception, TypeError given, called in /home/wwwroot/azure/vendor/yangweijie/think-debugbar/src/ExceptionHandle.php on line 64 and defined in /home/wwwroot/azure/vendor/maximebf/debugbar/src/DebugBar/DataCollector/ExceptionsCollector.php:30<br />
Stack trace:<br />
#0 /home/wwwroot/azure/vendor/yangweijie/think-debugbar/src/ExceptionHandle.php(64): DebugBar\DataCollector\ExceptionsCollector->addException()<br />
#1 /home/wwwroot/azure/vendor/topthink/framework/src/think/initializer/Error.php(53): think\debugbar\ExceptionHandle->report()<br />
#2 [internal function]: think\initializer\Error->appException()<br />
#3 {main}<br />
  thrown
```
降级到1.0.3版本，有错误
```
call_user_func_array(): Argument #1 ($callback) must be a valid callback, class think\Template does not have a method "getFinder"
```

环境
```
PHP 8.2.6 (cli) (built: Oct 19 2023 23:01:20) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.6, Copyright (c) Zend Technologies
```

```
Composer version 2.7.7 2024-06-10 22:11:12
```
